version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    networks:
      - dockerredis
  redis:
    image: redis
    container_name: dockerredis
    ports:
      - "6379:6379"
    networks:
      - dockerredis

networks:
  dockerredis:
    name: dockerredis
